version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    command: "go run main.go"
    volumes:
      - .:/go/src/work # マウントディレクトリ指定